# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docs:
    runs-on: windows-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore ./src/Imageflow.dncore.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore ./src/Imageflow.dncore.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal ./src/Imageflow.dncore.sln
    - run: choco install docfx -y
    - name: Build Documentation
      run: docfx .\docfx.json
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .
